version: "3.4"
services:
  orchestrator:
    image: ghcr.io/days-stickworld/orchestrator:main
    ports: 
      - "5041:80"
    environment:
      - REDIS_HOST=redis
      - PUBLIC_IP=127.0.0.1 # Aanpassen naar IP-adres waarop de orchestrator bereikbaar is.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
